### PR TITLE
global: addition of 'version', 'language' and 'grants' field update

### PR DESCRIPTION
**Pull request by krzysztof**
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>

### CODE REVIEW

**Comment by krzysztof** [comment]
<a href="https://i.imgur.com/BnjG4qY.png">
  
</a>

**Comment by krzysztof** [comment]
<a href="https://i.imgur.com/K9Uw4QA.png">
  
</a>

**Comment by krzysztof** [comment]
@slint can you take a look

**Comment by slint** [comment]
It might be worth mentioning the `/api/{grants/funders}` endpoints, so that users can search for grants/funders that are available on Zenodo for sure, since just formatting correctly a grant id won't be enough if the grant is not in our database

**Comment by krzysztof** [comment]
@slint I know, but the correct way is actually documenting the REST API for those... I don't want to expand this row to a page

**Pull request merged**
